import { Laptop, Smartphone, Monitor, Headphones, HardDrive, Cpu, Keyboard, Watch } from "lucide-react"

export const categories = [
  {
    icon: Laptop,
    name: "Laptops",
    slug: "laptops",
    count: 234,
    color: "from-blue-500/20 to-cyan-500/20",
    description: "Refurbished laptops from top brands",
    image: "/modern-laptop-computer-on-desk.jpg",
  },
  {
    icon: Smartphone,
    name: "Phones & Tablets",
    slug: "phones",
    count: 189,
    color: "from-purple-500/20 to-pink-500/20",
    description: "Smartphones and tablets ready for reuse",
    image: "/smartphone-and-tablet-devices.jpg",
  },
  {
    icon: Monitor,
    name: "Monitors",
    slug: "monitors",
    count: 156,
    color: "from-teal-500/20 to-emerald-500/20",
    description: "Display monitors in great condition",
    image: "/computer-monitor-display-screen.jpg",
  },
  {
    icon: Headphones,
    name: "Audio",
    slug: "audio",
    count: 98,
    color: "from-orange-500/20 to-amber-500/20",
    description: "Headphones, speakers, and audio gear",
    image: "/headphones-and-audio-equipment.jpg",
  },
  {
    icon: HardDrive,
    name: "Storage",
    slug: "storage",
    count: 145,
    color: "from-slate-500/20 to-gray-500/20",
    description: "External drives and storage solutions",
    image: "/external-hard-drive-storage-device.jpg",
  },
  {
    icon: Cpu,
    name: "Components",
    slug: "components",
    count: 267,
    color: "from-red-500/20 to-rose-500/20",
    description: "PC parts and components",
    image: "/computer-components-cpu-gpu-motherboard.jpg",
  },
  {
    icon: Keyboard,
    name: "Peripherals",
    slug: "peripherals",
    count: 312,
    color: "from-indigo-500/20 to-violet-500/20",
    description: "Keyboards, mice, and accessories",
    image: "/mechanical-keyboard-and-mouse.jpg",
  },
  {
    icon: Watch,
    name: "Wearables",
    slug: "wearables",
    count: 76,
    color: "from-green-500/20 to-lime-500/20",
    description: "Smartwatches and fitness trackers",
    image: "/smartwatch-wearable-technology.jpg",
  },
]

export const allListings = [
  {
    id: 1,
    title: "MacBook Pro 2019 - 16GB RAM",
    description:
      "Excellent condition MacBook Pro with 16GB RAM and 512GB SSD. Minor cosmetic wear on the bottom case. Battery health at 89%. Includes original charger.",
    condition: "Excellent",
    type: "Donation",
    location: "San Francisco, CA",
    postedAt: "2 hours ago",
    image: "/macbook-pro-laptop-silver-aluminum.jpg",
    images: [
      "/macbook-pro-laptop-silver-aluminum.jpg",
      "/macbook-pro-keyboard-top-view.jpg",
      "/macbook-pro-ports-side-view.jpg",
      "/macbook-pro-open-screen-display.jpg",
    ],
    category: "laptops",
    categoryName: "Laptops",
    donor: "TechCorp Inc.",
    donorAvatar: "/tech-company-logo-blue.png",
    specs: ["Intel Core i7", "16GB RAM", "512GB SSD", '15.6" Retina Display'],
    views: 234,
    requests: 12,
  },
  {
    id: 2,
    title: 'Dell 27" 4K Monitor',
    description:
      "Dell UltraSharp 27 4K USB-C Monitor. Excellent color accuracy, perfect for design work. Comes with stand and USB-C cable.",
    condition: "Good",
    type: "Free",
    location: "Oakland, CA",
    postedAt: "5 hours ago",
    image: "/dell-4k-monitor-black-display.jpg",
    images: ["/dell-4k-monitor-black-display.jpg", "/monitor-back-ports-connectors.jpg", "/monitor-stand-base.jpg"],
    category: "monitors",
    categoryName: "Monitors",
    donor: "StartupHub",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["27 inch 4K UHD", "USB-C", "60Hz", "IPS Panel"],
    views: 189,
    requests: 8,
  },
  {
    id: 3,
    title: "iPhone 12 Pro - 128GB",
    description:
      "iPhone 12 Pro in Pacific Blue. Screen is flawless with glass protector. Battery health at 94%. Unlocked for all carriers.",
    condition: "Like New",
    type: "Subsidized",
    location: "San Jose, CA",
    postedAt: "1 day ago",
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    category: "phones",
    categoryName: "Phones & Tablets",
    donor: "GreenTech Foundation",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["A14 Bionic", "128GB", "Unlocked", "5G Capable"],
    views: 312,
    requests: 24,
  },
  {
    id: 4,
    title: "Mechanical Keyboard - Cherry MX",
    description:
      "Full-size mechanical keyboard with Cherry MX Blue switches. RGB backlighting with software control. Great tactile feedback.",
    condition: "Good",
    type: "Free",
    location: "Berkeley, CA",
    postedAt: "1 day ago",
    image: "/placeholder.svg?height=400&width=600",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "peripherals",
    categoryName: "Peripherals",
    donor: "Anonymous",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["Cherry MX Blue", "Full RGB", "USB-C", "Wired"],
    views: 145,
    requests: 6,
  },
  {
    id: 5,
    title: "Samsung Galaxy Tab S7",
    description:
      "Samsung Galaxy Tab S7 with S Pen included. Perfect for students and professionals. Minor scratch on back panel.",
    condition: "Excellent",
    type: "Donation",
    location: "Palo Alto, CA",
    postedAt: "2 days ago",
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    category: "phones",
    categoryName: "Phones & Tablets",
    donor: "Education First NGO",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["Snapdragon 865+", "128GB", "S Pen Included", '11" Display'],
    views: 198,
    requests: 15,
  },
  {
    id: 6,
    title: "Sony WH-1000XM4 Headphones",
    description:
      "Industry-leading noise cancellation headphones. Includes carrying case, charging cable, and airplane adapter.",
    condition: "Like New",
    type: "Subsidized",
    location: "Mountain View, CA",
    postedAt: "3 days ago",
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    category: "audio",
    categoryName: "Audio",
    donor: "SoundWave Labs",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["Active Noise Cancellation", "30hr Battery", "Bluetooth 5.0", "Touch Controls"],
    views: 267,
    requests: 19,
  },
  {
    id: 7,
    title: "ThinkPad X1 Carbon Gen 9",
    description:
      "Business-class ultrabook in excellent condition. Powerful specs for professional work. Comes with docking station.",
    condition: "Excellent",
    type: "Donation",
    location: "Cupertino, CA",
    postedAt: "3 days ago",
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    category: "laptops",
    categoryName: "Laptops",
    donor: "Enterprise Solutions Co",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["Intel Core i7-1165G7", "16GB RAM", "512GB SSD", '14" 2K Display'],
    views: 178,
    requests: 11,
  },
  {
    id: 8,
    title: "Apple Watch Series 6",
    description:
      "Apple Watch Series 6 GPS + Cellular. Space Gray aluminum case. Includes multiple bands and original charger.",
    condition: "Good",
    type: "Subsidized",
    location: "Sunnyvale, CA",
    postedAt: "4 days ago",
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    category: "wearables",
    categoryName: "Wearables",
    donor: "FitLife Community",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["GPS + Cellular", "44mm", "Always-On Display", "Blood Oxygen Sensor"],
    views: 156,
    requests: 9,
  },
  {
    id: 9,
    title: "1TB External SSD",
    description: "Samsung T7 Portable SSD 1TB. Fast USB 3.2 Gen 2 speeds. Perfect for backup or extra storage.",
    condition: "Like New",
    type: "Free",
    location: "Fremont, CA",
    postedAt: "5 days ago",
    image: "/placeholder.svg?height=400&width=600",
    images: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    category: "storage",
    categoryName: "Storage",
    donor: "DataSafe Inc",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["1TB Capacity", "1050MB/s Read", "USB 3.2 Gen 2", "Shock Resistant"],
    views: 123,
    requests: 7,
  },
  {
    id: 10,
    title: "NVIDIA RTX 3070",
    description: "Gaming-grade graphics card. Used for light gaming. No mining history. Original box included.",
    condition: "Excellent",
    type: "Subsidized",
    location: "Santa Clara, CA",
    postedAt: "6 days ago",
    image: "/placeholder.svg?height=400&width=600",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    category: "components",
    categoryName: "Components",
    donor: "GameDev Studios",
    donorAvatar: "/placeholder.svg?height=100&width=100",
    specs: ["8GB GDDR6", "PCIe 4.0", "Ray Tracing", "DLSS Support"],
    views: 289,
    requests: 22,
  },
]

export const conditionColors: Record<string, string> = {
  "Like New": "bg-emerald-100 text-emerald-700 border-emerald-200",
  Excellent: "bg-blue-100 text-blue-700 border-blue-200",
  Good: "bg-amber-100 text-amber-700 border-amber-200",
}

export const typeColors: Record<string, string> = {
  Donation: "bg-primary text-primary-foreground",
  Free: "bg-green-500 text-white",
  Subsidized: "bg-blue-500 text-white",
}
